# Generated by Django 5.1.3 on 2024-12-29 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_time',
        ),
    ]
