# Generated by Django 5.1.3 on 2024-12-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_website', '0003_reservation_end_time_reservation_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
