# Generated by Django 5.1.3 on 2025-01-02 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe_website', '0004_alter_reservation_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='author',
            field=models.ManyToManyField(blank=True, to='cafe_website.author'),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
